version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.3.0
    steps:
      - checkout
      - run:
          name: Install dependecies
          command: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    machine:
      enabled: true
    docker:
      - image: circleci/node:8.3.0
    steps:
      - checkout
      - run:
          name: Check npm package version
          command: ./deploy/check-publish-version
      - run:
          name: Publish package to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm publish
            else
              echo "Not on master branch so not publishing to npm
            fi
# Ensure jobs are run sequentially
# Publish should only be run once and if tests pass
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy:
        requires:
          - build