version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout

        # This should go into custom primary image, here's only for the sake of explanation
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          command: |
            sudo -i
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            exit

      - run:
          name: Start container
          command: |
            set -x
            docker-compose up -d

      - run:
          name: Install dependecies
          command: npm install

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Stop container
          command: |
            set -x
            docker-compose down

  deploy:
    docker:
      - image: circleci/node:8.3.0
    steps:
      - checkout

      - run:
          name: Check npm package version
          command: ./deploy/check-publish-version

      - run:
          name: Publish package to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm publish
            else
              echo "Not on master branch so not publishing to npm
            fi
# Ensure jobs are run sequentially
# Publish should only be run once and if tests pass

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master