version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.3.0
    steps:
      - run: npm test
  publish:
    docker:
      - image: circleci/node:8.3.0
    steps:
      - run: ./deploy/check-publish-version
      - deploy:
          name: Publish package to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm publish
            else
              echo "Not on master branch so not publishing to npm
            fi
# Ensure jobs are run sequentially
# Publish should only be run once and if tests pass
workflows:
  version: 2
  test-&-publish:
    jobs:
      -test
      -publish:
        requires:
          - test